"""add conversation memory state

Revision ID: 4c0790a50ea2
Revises: d12997042023
Create Date: 2026-06-21 23:03:22.667598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0790a50ea2'
down_revision: Union[str, Sequence[str], None] = 'd12997042023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('memory_through_sequence_number', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('conversations', sa.Column('memory_update_status', sa.Text(), server_default=sa.text("'idle'"), nullable=False))
    op.add_column('conversations', sa.Column('memory_update_error', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('is_processing', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('conversations', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        'ck_conversations_memory_update_status',
        'conversations',
        "memory_update_status IN ('idle', 'pending', 'completed', 'failed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_conversations_memory_update_status',
        'conversations',
        type_='check',
    )
    op.drop_column('conversations', 'processing_started_at')
    op.drop_column('conversations', 'is_processing')
    op.drop_column('conversations', 'memory_update_error')
    op.drop_column('conversations', 'memory_update_status')
    op.drop_column('conversations', 'memory_through_sequence_number')
    # ### end Alembic commands ###
